prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix replacedBy: <http://purl.obolibrary.org/obo/IAO_0100001>

SELECT ?cls ?consider ?replacedBy WHERE 
{
  ?cls a owl:Class .
  ?cls owl:deprecated ?obs .
  OPTIONAL { ?cls oio:consider ?consider } .
  OPTIONAL { ?cls replacedBy: ?replacedBy } .
  FILTER(?obs = true)
}
