PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX never_in_taxon: <http://purl.obolibrary.org/obo/RO_0002161>
PREFIX present_in_taxon: <http://purl.obolibrary.org/obo/RO_0002175>

SELECT ?term ?taxon
WHERE {
  ?term never_in_taxon:|present_in_taxon: ?taxon .

  FILTER (!isIRI(?taxon) && (!STRSTARTS(STR(?taxon), "http://purl.obolibrary.org/obo/NCBITaxon_")))
}
