defaults:
  compositing:
    unfold_over:
      - RO:0002162
species:
  - taxon_id: NCBITaxon:9606
    label: human
    compositing:
      preserve:
        - RO:0002202
        - RO:0002496
        - RO:0002497
        - BFO:0000051
    bridging:
      - prefix: DHBA
        namespace: https://purl.brain-bican.org/ontology/dhbao/DHBA_
      - prefix: HBA
        namespace: https://purl.brain-bican.org/ontology/hbao/HBA_
      - prefix: EHDAA2
        label: embryonic human
      - prefix: HsapDv
      - prefix: FMA
        namespace: http://purl.org/sig/ont/fma/fma
        label: post-embryonic human
      - prefix: KUPO
  - taxon_id: NCBITaxon:10090
    label: mouse
    compositing:
      preserve:
        - RO:0002202
        - RO:0002496
        - RO:0002497
        - BFO:0000051
    bridging:
      - prefix: EMAPA
        label: embryonic mouse
      - prefix: MA
        label: post-embryonic mouse
      - prefix: MmusDv
  - taxon_id: NCBITaxon:7227
    label: D melanogaster
    bridging:
      - prefix: FBbt
      - prefix: FBdv
  - taxon_id: NCBITaxon:7399
    label: hymenoptera
    bridging:
      - prefix: HAO
  - taxon_id: NCBITaxon:9443
    label: primate
    bridging:
      - prefix: PBA
        namespace: https://purl.brain-bican.org/ontology/pbao/PBA_
  - taxon_id: NCBITaxon:6893
    label: spider
    bridging:
      - prefix: SPD
  - taxon_id: NCBITaxon:6939
    label: hardbacked ticks
    bridging:
      - prefix: TADS
  - taxon_id: NCBITaxon:44484
    label: mosquitos
    bridging:
      - prefix: TGMA
  - taxon_id: NCBITaxon:6237
    label: worm
    bridging:
      - prefix: WBbt
      - prefix: WBls
  - taxon_id: NCBITaxon:8353
    label: xenopus
    bridging:
      - prefix: XAO
  - taxon_id: NCBITaxon:7954
    label: zebrafish
    bridging:
      - prefix: ZFA
      - prefix: ZFS
  - taxon_id: NCBITaxon:28377
    label: anolis
    bridging:
      - prefix: AcarDv
        name: sslso
  - taxon_id: NCBITaxon:9913
    label: cow
    bridging:
      - prefix: BtauDv
        name: sslso
  - taxon_id: NCBITaxon:9615
    label: dog
    bridging:
      - prefix: CfamDv
        name: sslso
  - taxon_id: NCBITaxon:10141
    label: cavy
    bridging:
      - prefix: CporDv
        name: sslso
  - taxon_id: NCBITaxon:7217
    label: D ananassae
    bridging:
      - prefix: DanaDv
        name: sslso
  - taxon_id: NCBITaxon:7230
    label: D mojavensis
    bridging:
      - prefix: DmojDv
        name: sslso
  - taxon_id: NCBITaxon:7237
    label: D pseudobscura
    bridging:
      - prefix: DpseDv
        name: sslso
  - taxon_id: NCBITaxon:7240
    label: D simulans
    bridging:
      - prefix: DsimDv
        name: sslso
  - taxon_id: NCBITaxon:7244
    label: D virilis
    bridging:
      - prefix: DvirDv
        name: sslso
  - taxon_id: NCBITaxon:7245
    label: D yakuba
    bridging:
      - prefix: DyakDv
        name: sslso
  - taxon_id: NCBITaxon:9796
    label: horse
    bridging:
      - prefix: EcabDv
        name: sslso
  - taxon_id: NCBITaxon:9365
    label: hedgehog
    bridging:
      - prefix: EeurDv
        name: sslso
  - taxon_id: NCBITaxon:9685
    label: cat
    bridging:
      - prefix: FcatDv
        name: sslso
  - taxon_id: NCBITaxon:9031
    label: chicken
    bridging:
      - prefix: GgalDv
        name: sslso
  - taxon_id: NCBITaxon:9593
    label: gorilla
    bridging:
      - prefix: GgorDv
        name: sslso
  - taxon_id: NCBITaxon:13616
    label: opossum
    bridging:
      - prefix: MdomDv
        name: sslso
  - taxon_id: NCBITaxon:9544
    label: macaque
    bridging:
      - prefix: MmulDv
        name: sslso
  - taxon_id: NCBITaxon:9258
    label: platypus
    bridging:
      - prefix: OanaDv
        name: sslso
  - taxon_id: NCBITaxon:9940
    label: sheep
    bridging:
      - prefix: OariDv
        name: sslso
  - taxon_id: NCBITaxon:9986
    label: rabbit
    bridging:
      - prefix: OcunDv
        name: sslso
  - taxon_id: NCBITaxon:8090
    label: medaka
    bridging:
      - prefix: OlatDv
        name: sslso
  - taxon_id: NCBITaxon:6358
    label: Platynereis
    bridging:
      - prefix: PdumDv
        name: sslso
  - taxon_id: NCBITaxon:9597
    label: bonobo
    bridging:
      - prefix: PpanDv
        name: sslso
  - taxon_id: NCBITaxon:9600
    label: orangutan
    bridging:
      - prefix: PpygDv
        name: sslso
  - taxon_id: NCBITaxon:9598
    label: chimpanzee
    bridging:
      - prefix: PtroDv
        name: sslso
  - taxon_id: NCBITaxon:10116
    label: rat
    bridging:
      - prefix: RnorDv
        name: sslso
  - taxon_id: NCBITaxon:8030
    label: salmon
    bridging:
      - prefix: SsalDv
        name: sslso
  - taxon_id: NCBITaxon:9823
    label: pig
    bridging:
      - prefix: SscrDv
        name: sslso
  - taxon_id: NCBITaxon:99883
    label: tetraodon
    bridging:
      - prefix: TnigDv
        name: sslso
  - taxon_id: NCBITaxon:9925
    label: goat
    bridging:
      - prefix: ChirDv
        name: sslso
