name: 'Explain taxon constraint violations'

on:
  # Only run upon completion of the main CI workflow
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]

jobs:
  explain_tc:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.4.3

    # Only run if the CI workflow was triggered on a PR and it failed
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - uses: actions/checkout@v2

      - name: Perform taxon constraint check
        id: check
        continue-on-error: true
        run:
          cd src/ontology && makedir -p tmp reports mirror && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' GH_ACTION=true MIR=false IMP=false BRI=false reports/taxon-constraint-check.txt

      - name: Reason over taxon constraints
        id: reason
        continue-on-error: true
        run: |
          if [ -s src/ontology/reports/taxon-constraint-check.txt ]; then
            robot explain -i src/ontology/tmp/uberon-edit-plus-tax-equivs.owl -M unsatisfiability -u all -r ELK -e taxon-unsats.md
            echo "<details>\n<summary>This PR violates some taxon constraints. Here is what the reasoner has to say:</summary>\n" > comment.md
            cat taxon-unsats.md >> comment.md
            echo "</details>" >> comment.md
            exit 1
          fi

      - name: Post explanation for taxon constraint violations
        if: ${{ steps.reason.outcome == 'failure' }}
        uses: NejcZdovc/comment-pr@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          file: "../../comment.md"
          identifier: "TAXON_CONSTRAINTS_REASONING"
